// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package pkg

type EvaluateInput struct {
	Sfen          string   `json:"sfen"`
	Moves         []string `json:"moves"`
	TimeoutSecond int      `json:"timeoutSecond"`
}

type EvaluateOutput struct {
	Value    int      `json:"value"`
	Bestmove string   `json:"bestmove"`
	Pv       []string `json:"pv"`
}
