name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1.9.0
        with:
          registry: asia.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build
        run:
          docker build -t gcr.io/shogi-kenkyu/apery-graphql .
      - name: Push
        run:
          docker push gcr.io/shogi-kenkyu/apery-graphql
